/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/my/index" |
       "/pages/template/index" |
       "/sub-pages/axios/index" |
       "/sub-pages/detail/index" |
       "/sub-pages/login/index" |
       "/sub-pages/route/index" |
       "/sub-pages/route/query";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: '/pages/index/index' | '/pages/template/index' | '/pages/my/index';
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
